version: '3'
services:
   mongodb:
      image: mongo:7.0.1-jammy
      container_name: fcc-fastify-mongodb
      environment:
         MONGO_INITDB_ROOT_USERNAME: admin
         MONGO_INITDB_ROOT_PASSWORD: passwd
         MONGO_INITDB_DATABASE: init
      hostname: ffmongodb
      ports:
         - 3087:27017
      volumes:
         - fcc-fastify-mongodb-data:/data/db

   mongo-express:
      image: mongo-express
      container_name: fcc-fastify-mongo-express
      depends_on:
         - mongodb
      environment:
         ME_CONFIG_MONGODB_ADMINUSERNAME: admin
         ME_CONFIG_MONGODB_ADMINPASSWORD: passwd
         ME_CONFIG_MONGODB_URL: mongodb://admin:passwd@ffmongodb:27017/
         ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ports: 
         - 3081:8081
volumes:
   fcc-fastify-mongodb-data:
